version: 2
jobs:
  build:
    docker:
      - image: kpndigital/tox:master
        environment:
          TOX_PY27: '2.7.13'
          TOX_PY35: '3.5.3'
          TOX_PY36: '3.6.1'

    steps:
      - checkout
      - run: pip -V
      - run: pip install -U pip
      - run: pip install -U tox
      - run: pip install -U .
      - run: pyenv local $TOX_PY27 $TOX_PY35 $TOX_PY36
      - run: tox -v --recreate
